from pathlib import Path
from PIL import Image
import json
ROOT=Path(__file__).parent
ASSETS=ROOT/'assets';ASSETS.mkdir(exist_ok=True,parents=True)
images={
 'day':'exec-3d48ba87-b5c9-45de-8fe3-8b6f7b390fab.png',
 'giant':'exec-cade3edd-346a-49d1-b586-5c97fc95fe79.png',
 'fish':'exec-aed341f5-3d40-40b6-9292-c1fabc49a29f.png',
 'pigeon':'exec-a853b184-843f-4340-bde4-a07d4ae78541.png',
 'guest':'exec-663ca002-96e2-419f-ad50-e93dfa114331.png',
 'curtain':'exec-3d9762ca-571e-4cd8-aceb-d0b91a36d071.png',
 'box':'exec-f0317f98-fa6b-4f98-b73f-41399e8da0b7.png'}
for name,src in images.items():
 im=Image.open(ROOT.parent/'generated_images'/src).convert('RGB');im.thumbnail((1280,720));im.save(ASSETS/f'{name}.jpg',quality=94)
COMMON='''Create ONE polished 5-second 16:9 2D anime narrative shot. Preserve exact reference identity and clothing: young adult black-haired shopkeeper, cream cable-knit cardigan, white shirt, loose dark-red striped tie, charcoal paw apron. ONE black cat with golden eyes and gold star collar. Include ONLY the exact cast listed for this shot. Keep the exact species and design in the supplied reference. No extra figures or animals. Bright gentle daylight, balanced warm-neutral movie light, clean linework. Location INSIDE same wooden pet shop, teal counter, CLOSED back door, cream bench, shelves. No outdoor cutaways, no spontaneous exits. Maintain object positions and current action state specified below. No captions, no written dialogue, no text overlays, no speech bubbles. No comic panels or photo slideshow. Single continuous shot, NO cuts to another scene or person. Physical actions continue, do not restart; small expressive pauses and lively cute acting. One designated speaker only, visible speaking face or beak, accurate synchronized mouth. All listeners mouths CLOSED, reactions via eyes/brows/body. No narration or spoken role labels. Natural clear Mandarin voice matching the designated speaker. Low gentle whimsical pizzicato/woodwind music, dialogue clearly louder, appropriate soft cartoon Foley. Do not read English directions aloud. Do not introduce any extra spoken words. All intentional character names INSIDE quoted dialogue must remain audible. Only the exact quoted sentence is spoken once. No labels before it.'''
CAST={2:'EXACT CAST: one shopkeeper, one black cat, one yellow goggle duck, one white round fluffy bell creature. FOUR characters total.',3:'EXACT CAST: one shopkeeper, one black cat, one yellow goggle duck on counter, one white fluffy creature sleeping on distant bench. FOUR characters total.',4:'EXACT CAST: one shopkeeper, one black cat, one light-gray sleepy pigeon. THREE characters total.',5:'EXACT CAST: one black-haired shopkeeper, one black cat, one mint-green long-eared RABBIT, one ADULT brown-haired guest with thin round glasses, mint hoodie, navy jeans, white sneakers. FOUR characters total. Rabbit keeps narrow long ears and reference design.'}
episodes=[]
def make(ep,title,rule,rows):
 clips=[]
 for idx,row in enumerate(rows,1):
  ref,speaker,zh,en,action,*previous=row
  c={'id':f'{ep:02}_{idx:02}','episode':ep,'shot':idx,'duration':5,'reference':f'assets/{ref}.jpg','speaker':speaker,'zh':zh,'en':en,'action':action}
  if previous and previous[0]:c['previous_frame']=f'{ep:02}_{previous[0]:02}'
  c['prompt']=COMMON+'\n'+CAST[ep]+'\nCONTINUITY AND RULE: '+rule+'\nSHOT ACTION: '+action+'\nONLY SPEAKER: '+speaker+'. Exact audible Mandarin sentence: “'+zh+'”'
  clips.append(c)
 episodes.append({'episode':ep,'title':title,'rule':rule,'clips':clips})
make(2,'千万别再说“我没事”','White fluff grows only when a person hides genuine exhaustion behind a denial. Merely explaining the rule does not trigger it. Honest admission makes it shrink. Size never resets between adjacent shots. The newest complaint slip was delivered after last episode night; now morning.',[
 ('day','shopkeeper','第四百一十八号：投诉我不肯休息？','Number 418: a complaint that I refuse to rest?','Medium on tired man RIGHT behind counter, he reads the small complaint slip, eyebrows rise; one long weary blink, then baffled smile. Cat on left counter. Duck and SMALL white fluff on floor. Show paper without legible writing.'),
 ('day','shopkeeper','煤球，我没事，我还能再看十份。','Meiqiu, I am fine. I can read ten more.','Man puts complaint slip onto stack, forces cheerful thumbs-up while visibly tired. In response to denial, white fluff on floor slowly puffs from 30 cm to 60 cm. It remains ONE creature. Cat watches silently. End fluff 60 cm, man behind counter.'),
 ('day','black cat','它叫团团。你硬撑说没事，它就变大。','This is Tuantuan. Pretend you are fine, and it grows.','Continue 60 cm white fluff state. Close-up on black cat LEFT counter speaking to man. Camera includes fluff below and man closed-mouth reaction at edge. Cat points one paw down to introduce fluff. Fluff does not grow during explanation.',2),
 ('day','shopkeeper','哪有硬撑？我真的没事！','Pretending? I really am fine!','Continue fluff 60 cm. Man moves around RIGHT end of counter to customer side floor, protests with empty hands. White fluff visibly inflates to sofa-width 1.3 m tall with soft boing, nudging man harmlessly toward right bench. End man on front-right floor next to GIANT fluff.',2),
 ('giant','shopkeeper','团团，别长了！你快比我的店还贵了！','Tuantuan, stop growing! You will cost more than my shop!','GIANT white fluff floor center, man front RIGHT squeezed safely beside cream bench. Medium two-shot, he measures its ridiculous width with his arms and stares at expensive shelving. Fluff innocently blinks, no more growth. Cat left counter, duck floor left.'),
 ('giant','black cat','萌萌谈，别按它。它不是漏气的抱枕。','Mengmeng Tan, stop squeezing. It is not a leaky cushion.','Close-medium on black cat LEFT counter. Behind, man gently presses giant soft fluff with palms; fur indents and rebounds to SAME size, no deflation. Cat gives stern one-paw stop gesture. Man silent, mouth CLOSED. Never hurt any creature.'),
 ('giant','yellow duck','嘎！再挤一下，店长就变书签了！','Quack! One more squeeze and the owner is a bookmark!','Low close-up on goggle duck floor LEFT, it holds wings very close to illustrate a thin bookmark. Giant fluff fills background. Man far RIGHT gives silent comic side-eye, no injury, no literal transformation. Cat silent.'),
 ('giant','black cat','说实话。萌萌谈，你到底累不累？','Tell the truth, Mengmeng Tan. Are you tired?','Close-medium on cat left counter, sternness softens, ears relax. It looks directly at tired man front-right, waiting without scolding. White fluff remains giant and still. Man closed mouth, shoulders sag.'),
 ('giant','shopkeeper','累。我想躺着，连翻身都想外包。','Exhausted. I want to outsource even turning over.','Man front-right finally admits exhaustion, hands drop, honest relieved expression. During second half, the ONE giant fluff smoothly SHRINKS all the way to original 30 cm size on FLOOR. No disappearance or duplicate. End man free beside bench, small fluff looking up; cat counter and duck left.'),
 ('giant','shopkeeper','团团，谢谢。给我十分钟，好吗？','Thanks, Tuantuan. Give me ten minutes, okay?','Continue previous final frame: white fluff already SMALL, never re-inflate. Man bends, gently lifts small fluff, sits visibly on nearby cream bench RIGHT and settles it on lap while speaking. One uninterrupted action. End sitting, cat stays counter, duck floor.',9),
 ('day','black cat','准假。投诉单我看，你负责休息。','Leave approved. I will read. Your job is to rest.','Continue seated man on RIGHT bench, SMALL white fluff in lap. Camera pans gently to cat LEFT counter pulling paper stack toward itself with one paw. Cat speaks kindly in official voice. Man closes eyes, relaxed closed mouth, no standing.',10),
 ('day','yellow duck','嘘……店长已关机，暂不接受加班。','Shh... The owner is offline. No overtime accepted.','Continue man asleep on bench with small white fluff lap. Duck tiptoes toward bench, turns to camera and whispers line with one wing by beak. Fluff curls against man, cat quietly sorts papers in background. End duck shuts beak with proud tiny nod. No waking, no regrowth.',11)
])
make(3,'这只鸭子会把真心话喊出来','Duck repeats a current concealed feeling only after someone speaks its opposite. It is not omniscient and does not reveal unrelated factual histories. Honest words give nothing to expose. ONE fish pouch stays same throughout; white fluff asleep on distant bench.',[
 ('fish','shopkeeper','这包小鱼干，绝对不是给煤球的。','These dried fish are definitely not for Meiqiu.','Man RIGHT shyly hides ONE clear fish pouch behind his back, cheeks pink. Cat LEFT notices. Duck CENTER raises eyebrow, ready to expose lie. Keep man only speaker, others mouths closed. End pouch behind back.'),
 ('fish','yellow duck','嘴嘴播报：他怕煤球又不吃早饭！','Zuizui reporting: he worries Meiqiu skips breakfast!','Close-up goggle duck CENTER counter acts like tiny newscaster, holds one wing as imaginary microphone and announces. Man right holding SAME pouch partly behind back recoils silently; cat left silent. No real microphone.'),
 ('fish','black cat','嘴嘴，别把人家的心里话当广播。','Zuizui, private feelings are not a radio show.','Close-up cat LEFT counter gives duck a dignified side-eye and gently lowers its raised wing with one paw. Man right and pouch remain, no eating or new props. Duck beak CLOSED listening.'),
 ('fish','shopkeeper','我也没特地挑它爱吃的！','I did not specially pick his favorite either!','Man RIGHT lifts SAME fish pouch, spots cat staring and hastily holds it nearer his chest, embarrassed defensive expression. Duck CENTER visibly inhales for next broadcast but no duck words yet. Cat silent.'),
 ('fish','yellow duck','真心话：快夸我细心！','His real thought: please praise my thoughtfulness!','Duck CENTER leans forward, joyfully broadcasts, then points wing at man. Man blushes and ducks head silently, cat watches deadpan. One purposeful close-up on duck, no other speech.'),
 ('fish','shopkeeper','嘴嘴，你是鸭子，还是随身扩音器？','Zuizui, are you a duck or a portable loudspeaker?','Medium man RIGHT mock-exasperated, lowers pouch onto countertop in front of CAT LEFT and cups EMPTY hands around his own ears as if sound too loud, no covering or squeezing duck. Duck proud silent pose. End pouch on counter LEFT.'),
 ('fish','black cat','它只拆反话。你直说，它就没得播。','It exposes denial. Be honest and there is no broadcast.','Cat LEFT speaks calmly, one paw rests beside SAME fish pouch now on counter, not on or in mouth. Duck CENTER listens with CLOSED beak, man RIGHT embarrassed. No fish eating yet.'),
 ('fish','shopkeeper','煤球，送你的。谢谢你替我看投诉单。','Meiqiu, this is for you. Thanks for reading the complaints.','Man RIGHT looks directly at cat LEFT, honestly smiles and slides SAME fish pouch the last few centimeters toward cat. End pouch against cat paw. Duck CENTER closes beak, has nothing to announce. No additional speech.'),
 ('fish','black cat','礼物收下。夸奖，按规定当面发。','Gift accepted. Praise must be delivered in person.','CONTINUE pouch at CAT LEFT paw from previous shot. Cat places one paw firmly on pouch, mock-official serious face, then raises other paw toward man. Duck silent, man listening with closed mouth. No resetting pouch to man hand.',8),
 ('fish','black cat','萌萌谈，你挺会照顾人的。','Mengmeng Tan, you are good at caring for others.','Continue exact previous state. Cat gently pats man extended sleeve near countertop and says sincere line, eyes soften. Man gives small touched smile with CLOSED mouth; duck CENTER quietly watches, pouch stays beside cat.',9),
 ('fish','shopkeeper','我才没有很开心。','I am not that happy.','Continue pouch beside cat, man tries to hide delighted smile by looking away, cheeks red, fingers fidget at apron. Duck turns slowly toward camera, recognizes obvious denial. Cat closed-mouth amused gaze.',10),
 ('fish','yellow duck','嘎！他想把这句话裱起来！','Quack! He wants that compliment framed!','Continue same positions, duck triumphantly spreads wings like a picture frame and blurts punchline. Man covers his OWN blushing face with EMPTY hands, shoulders shaking in silent embarrassment. Cat pleased blink. Pouch stays with cat. Cute ending, no extra dialogue.',11)
])
make(4,'拖延鸽把咖啡推迟了五分钟','Each audible pigeon yawn postpones nearby queued work by five minutes. Rest is explicitly exempt. Sleep prevents more yawns but an existing delay must still elapse. Later shot marked FIVE MINUTES LATER releases machine. All stay indoors, one cat, one pigeon, one man.',[
 ('pigeon','shopkeeper','我的咖啡，怎么还在酝酿人生？','Why is my coffee still contemplating life?','Man RIGHT presses blue espresso machine button once. EMPTY blue mug remains under spout, nothing pours. He stares at mug, then at sleepy pigeon CENTER atop complaint papers, cat LEFT. No coffee yet.'),
 ('pigeon','gray pigeon','我叫灰五。先等五分钟……哈啊。','I am Huiwu. Wait five minutes... Yawn.','Close-up ONE gray sleepy pigeon on papers CENTER. It introduces itself slowly, then one clearly audible wide beak yawn on final syllable; soft blue ripple toward idle machine. Man and cat mouths CLOSED. Cup stays empty.'),
 ('pigeon','black cat','灰五打哈欠，工作晚五分钟，休息不算。','Huiwu yawns: work waits five minutes. Rest is exempt.','Cat LEFT counter explains with one paw raised, pigeon CENTER half asleep, man RIGHT looks at idle machine then pigeon. One gentle rack focus, all listeners mouths closed. No new yawn during this line.'),
 ('pigeon','shopkeeper','煤球，连我的午饭也在排队？','Meiqiu, is even my lunch in the queue?','Man RIGHT gestures helplessly at empty coffee mug and a small CLOSED lunch box beside machine. He checks wristwatch, then slumps. Cat left and pigeon center stay. Machine does not pour, pigeon does not yawn.'),
 ('pigeon','gray pigeon','昨晚……有人拿我压投诉单。','Last night... someone used me as a paperweight.','Pigeon CENTER sleepy close-up, lifts one tiny wing to reveal edge of paper under belly, then side-eyes black cat. Its feathers ruffled in comic overwork. No yawn, no magic. Man listens silently.'),
 ('pigeon','black cat','我以为，你是个会打呼的镇纸。','I thought you were a snoring paperweight.','Cat LEFT looks at paper stack, freezes one beat in embarrassed realization, straightens star badge and delivers deadpan excuse. Pigeon gives silent offended half-lidded stare. Man closed-mouth incredulous look. No moving props.'),
 ('pigeon','shopkeeper','喝咖啡醒醒……不对，咖啡也没开始！','Have coffee to wake up... Oh, it has not started either!','Man RIGHT reaches toward EMPTY mug then stops BEFORE picking it up; points at silent machine and realizes circular plan. Keep mug under spout, pigeon on paper, cat left. No feeding bird coffee, no new cup.'),
 ('pigeon','black cat','别等咖啡了。萌萌谈，先让灰五睡。','Forget coffee, Mengmeng Tan. Let Huiwu sleep first.','Cat LEFT points one paw at cream bird cushion to RIGHT of paper stack near machine. Man nods silently with closed mouth. Pigeon still on paper, cup empty. Simple clear plan, no yawn.'),
 ('pigeon','shopkeeper','文件我来压。灰五，你去睡。','I will hold the papers. Huiwu, go to sleep.','Man RIGHT gently lifts pigeon from paper stack with both hands, places it physically onto small cream bird cushion RIGHT side of counter away from coffee spout, then sets one EMPTY palm on paper stack. Continuous movement, no teleport. End pigeon on cushion, papers held by man.'),
 ('pigeon','gray pigeon','这次真的睡，不是准备睡。','This time I am sleeping, not preparing to sleep.','Continue pigeon already ON CREAM CUSHION right counter, no return to papers. Close-up pigeon tucks beak gently into wing, closes eyes and settles asleep after speaking. Man palm on paper, cat left, coffee cup still empty. NO yawn.',9),
 ('pigeon','black cat','五分钟到了，咖啡终于肯上班了。','Five minutes are up. The coffee finally starts work.','Time ellipsis: FIVE MINUTES LATER, same camera and room. Continue pigeon asleep on cushion, never yawn. Blue espresso machine now starts and pours coffee visibly INTO same blue mug. Cat LEFT speaks dryly and looks at machine, man RIGHT relaxes with head dipping. No textual clock generated; editor adds time caption.',10),
 ('pigeon','black cat','萌萌谈，咖啡好了。……人下班了。','Mengmeng Tan, coffee is ready... He has clocked out.','Continue coffee poured into mug and pigeon asleep cushion. Man RIGHT gently lowers forehead onto his folded arms on counter and falls asleep, not vanishing. Cat looks from ready coffee to sleeping man and delivers punchline, then tiny fond blink. Pigeon stays asleep. No new yawn or time magic.',11)
])
make(5,'社恐兔把顾客传送没了','Mint rabbit teleports its anxious owner into a nearby safe out-of-view spot INSIDE shop, never roof or dangerous shelf. A person touching owner is carried too. Stop staring and allow writing to lower anxiety. Jokes target overhelpful magic, not disability. Only adult owner, adult guest, black cat and mint rabbit.',[
 ('guest','shopkeeper','你好，我叫萌萌谈。你怎么称呼？','Hi, I am Mengmeng Tan. What is your name?','Man RIGHT behind counter politely introduces himself. Guest LEFT looks overwhelmed, mint rabbit ears stiffen. At end a soft mint puff relocates guest AND rabbit from customer spot to behind teal curtain rear LEFT. Clearly show empty original spot and guest silhouette behind curtain, cat remains RIGHT counter. Man does not teleport.'),
 ('guest','black cat','它叫逃逃。一紧张，就带主人躲起来。','This is Taotao. When anxious, it hides its owner.','Continue guest and rabbit already behind rear-left curtain, original customer spot EMPTY. Close-up cat RIGHT counter explains, glances at curtain. Man still behind counter RIGHT, mouths of others CLOSED. No additional teleport.',1),
 ('curtain','shy guest','我不是不理你。一被盯着，就紧张。','I am not ignoring you. Being watched makes me nervous.','Guest peeks from teal curtain LEFT and speaks softly, fingers holding curtain edge; rabbit at shoes. Shopkeeper has walked over and stands RIGHT at respectful arm length, listens with closed mouth. Cat on counter RIGHT. Large empty floor box nearby. No touch yet.'),
 ('curtain','shopkeeper','那我小声一点。这样呢？','Then I will speak more softly. Like this?','Same curtain stage. Man RIGHT lowers voice and gently touches guest LEFT forearm with EMPTY right hand. Rabbit becomes flustered, mint puff surrounds BOTH men and rabbit. Show curtain spot empty after puff, then camera pans LEFT to reveal both crouched safely in nearby large floor cardboard box, rabbit outside. No roof, no duplicate bodies.'),
 ('box','shopkeeper','我只是扶你一下，怎么连我也打包了？','I only steadied you. Why am I packed too?','Start exact box reference: guest LEFT inside roomy box, shopkeeper RIGHT inside, rabbit on floor front, cat counter behind. Man looks at box flaps and his bent knees in comic disbelief and speaks. Guest stays silent, no mockery, no new teleport.'),
 ('box','black cat','你碰着他。逃逃把你也当随身行李了。','You touched him. Taotao counted you as carry-on luggage.','Cat RIGHT counter delivers deadpan explanation; framing includes TWO men still in floor box at LEFT. Man silently looks at his own hand, guest apologetic but gently reassured by eye contact. Rabbit ears lower. No touching or teleport.'),
 ('box','shopkeeper','是我们围得太近了。大家，退后一点。','We crowded him. Everyone, give him some space.','Man RIGHT inside box rises carefully and steps OUT onto floor, then offers space while guest stands and steps out independently, no hand grabbing. Both clearly exit box; rabbit stays at guest shoes. End both standing outside box, empty box remains floor. One continuous wide shot.'),
 ('guest','shopkeeper','不用急着说，写给我也可以。','No rush to speak. You can write it down.','Continue both men OUT of box, guest near curtain. Shopkeeper walks back toward counter RIGHT, picks up clipboard and offers it at comfortable distance without touching guest, then steps back. Guest takes clipboard. Rabbit ears relax, cat averts gaze politely. Door closed.',7),
 ('guest','black cat','小安，一袋猫粮。收到。','Xiao An. One bag of cat food. Got it.','At counter again, guest LEFT holds clipboard and visibly writes a short note, mouth CLOSED. Camera does not show legible written text, shows his pen gesture and relaxed smile. Cat RIGHT counter reads the note aloud. Man RIGHT listens. Sealed beige fish-icon cat-food bag stays on counter. Rabbit at guest feet, no teleport.'),
 ('guest','shopkeeper','小安，下次指给我看也行。','Xiao An, next time you can point to what you need.','Continue guest LEFT with clipboard, man RIGHT behind counter. Guest sets clipboard down. Man gently slides SAME sealed cat-food bag across counter; guest takes it with BOTH hands. No money or new objects, no touching people, rabbit calm.',9),
 ('guest','shy guest','谢谢你，萌萌谈。','Thank you, Mengmeng Tan.','Continue guest LEFT HOLDING cat-food bag, he softly thanks shopkeeper and gives small relieved nod. Shopkeeper RIGHT smiles with mouth CLOSED. Rabbit leans against guest ankle, ears soft, cat watches kindly. Everyone stays inside, no door exit.',10),
 ('guest','black cat','逃逃，写报告也能申请撤离吗？','Taotao, can report-writing qualify for evacuation too?','Continue same settled state. Cat RIGHT counter notices clipboard, glances at rabbit on floor LEFT and asks with exaggerated official seriousness. Rabbit tilts head and covers its own blushing face with long ears; man and guest give silent amused smiles. NO teleport, no disappearing cast. End on cute rabbit reaction.',11)
])
cfg={'title':'萌萌谈与全城精灵','credit':'制作：林爱丽','model':'wan3.0-video','resolution':'480P','episodes':episodes,'max_paid_seconds':240,'pilot_ids':['02_09','03_02','04_02','05_01']}
assert all(len(e['clips'])==12 for e in episodes)
(ROOT/'episodes.json').write_text(json.dumps(cfg,ensure_ascii=False,indent=2))
print('Wrote 48 shots, 240 seconds, 7 reference scenes')
